Chat controls
0x0ade/CelesteNet pull request #11
Opened 2021-08-29 15:38 UTC by RedFlames

- `Left`/`Right` arrow keys move cursor
 - `Ctrl-Left`/`Ctrl-Right` moves cursor between words

 - `Backspace` works at cursor of course
 - `Ctrl-Backspace` removes entire word

 - `Delete` key works as one would expect
 - `Ctrl-Delete` removes entire word

there's also some extra logic so that holding down a direction has an initial delay before continuous movement

2021-11-04 14:23 UTC, 0x0ade requested changes
Sorry for the late response, and thank you for this pull request :) It looks good to me apart from the spacing mismatches.

I don't know if I would've gone for the `CursorIndex` setter to default to wrapping, would've probably gone for clamping instead 😅 I'm fine with it as is though.

2021-11-04 14:23 UTC, 0x0ade commented on CelesteNet.Client/Components/CelesteNetChatComponent.cs
> +                if(!MInput.Keyboard.Check(Keys.Left) && !MInput.Keyboard.Check(Keys.Right)) {
Please change the spacing here to match the rest of the project 😅 

```suggestion
                if (!MInput.Keyboard.Check(Keys.Left) && !MInput.Keyboard.Check(Keys.Right)) {
```

2021-11-04 14:23 UTC, 0x0ade commented on CelesteNet.Client/Components/CelesteNetChatComponent.cs
> +                if(CursorIndex == Typing.Length) {
Please change the spacing here to match the rest of the project 😅 

```suggestion
                if (CursorIndex == Typing.Length) {
```

2021-11-04 14:23 UTC, 0x0ade commented on CelesteNet.Client/Components/CelesteNetChatComponent.cs
> +                    if(CursorIndex == Typing.Length) {
Please change the spacing here to match the rest of the project 😅 

```suggestion
                    if (CursorIndex == Typing.Length) {
```

2021-11-09 19:22 UTC, RedFlames commented
Hey, glad to hear there are no major objections :)

> I don't know if I would've gone for the `CursorIndex` setter to default to wrapping, would've probably gone for clamping instead 😅 I'm fine with it as is though.

I'm 100% certain if the cursor actually ever wrapped around I'd go crazy 😬 I think I just took the modulo clamping from elsewhere to make sure the index never goes out of bounds for the input string. It looks like in all the places it _could_ wrap in theory, like pressing Left/Right I put extra comparisons against Typing.Length to prevent any wrapping 😅 
So I suppose I can also make the setter clamp instead of wrap.

I'll fix the mismatching whitespace asap, no problem.

2021-11-13 23:08 UTC, 0x0ade approved these changes
Thank you for fixing the whitespace issues, changing the `CursorIndex` setter behavior and this PR in general :)

2021-11-13 23:08 UTC, merged