Player opacity0
0x0ade/CelesteNet pull request #12
Opened 2021-10-22 08:50 UTC by cobo105322

This option would be useful if you want others to see you, but not see others, for example at a particularly focus-heavy section.

2021-11-04 14:17 UTC, 0x0ade requested changes

2021-11-04 14:17 UTC, 0x0ade commented on CelesteNet.Client/Entities/Ghost.cs
> +            }
Thanks for the pull request :) It'd be great if you could fix the spacing to match the rest of the code:

```suggestion
            if (CelesteNetClientModule.Settings.PlayerOpacity == 0) {
                Alpha = 0f;
            } else {
                Alpha = 0.875f * ((CelesteNetClientModule.Settings.PlayerOpacity + 2) / 6f);
            }
```

In the worst case I'll just fix the spacing myself before or after hitting the merge button.

2021-11-12 20:59 UTC, cobo105322 commented
Hey Jade, I commited your changes request for the spacing :)

2021-11-13 23:06 UTC, 0x0ade approved these changes
Thank you :)

2021-11-13 23:06 UTC, merged